#!/bin/bash -e

# Enter the kernel build directory
kpath=$(find /builddir/build/BUILD -type f -name Makefile -printf "%h\n" | sort | head -1)
cd ${kpath}

# Get the kernel's version string
kver=$(make kernelversion)

echo Generating config for kernel $kver

FIRST_FRAGMENTS=()

# Mandatory fragments are applied last, to take precedence
MANDATORY_FRAGMENTS=()

# Find best match of config fragments
for fragment in /usr/share/kernel-config/*; do
	vermatch=${fragment##*-}

	# Check whether vermatch is a substring of kernel version
	if [[ ${kver} != ${kver#${vermatch}} ]]; then
		filename=$(basename ${fragment})
		if [[ ${filename%%-*} == "mandatory" ]]; then
			echo Adding mandatory fragment $fragment
			MANDATORY_FRAGMENTS+=($fragment)
		else
			echo Adding initial fragment $fragment
			FIRST_FRAGMENTS+=($fragment)
		fi
	fi
done

echo Merging "${FIRST_FRAGMENTS[@]}" "$@" "${MANDATORY_FRAGMENTS[@]}"
./scripts/kconfig/merge_config.sh "${FIRST_FRAGMENTS[@]}" "$@" "${MANDATORY_FRAGMENTS[@]}"

echo Tagging generated config
echo >> .config
echo "# kernel-config sources:" >> .config
grep -h "FILEVER" "${FIRST_FRAGMENTS[@]}" "${MANDATORY_FRAGMENTS[@]}" >> .config
